import exceptions.blogpost.example4.errorHandlingExampleMain

fun main(args: Array<String>) {
    errorHandlingExampleMain()
}